apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: esplora-liquid
  name: esplora-liquid
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: esplora-liquid
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: esplora-liquid
    spec:
      containers:
        - env:
            - name: API_URL
            - name: IS_ELEMENTS
              value: "1"
            - name: NATIVE_ASSET_ID
              value: 5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225
          image: vulpemventures/esplora:latest
          name: esplora-liquid
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
