apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: hasura
  name: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hasura
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: hasura
    spec:
      containers:
        - env:
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              value: liquidart
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgres://postgres:postgrespassword@postgres:5432/postgres
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            - name: HASURA_GRAPHQL_JWT_SECRET
              value: '{"type": "HS256", "key": "25C134A00CF05C9BF583727A12778F52D0E7BD560D3A3ACF8E79127E9A56119D"}'
            - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
              value: anonymous
          image: hasura/graphql-engine:v2.0.9.cli-migrations-v3
          name: hasura
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /hasura-migrations
              name: hasura-claim0
            - mountPath: /hasura-metadata
              name: hasura-claim1
      restartPolicy: Always
      volumes:
        - name: hasura-claim0
          persistentVolumeClaim:
            claimName: hasura-claim0
        - name: hasura-claim1
          persistentVolumeClaim:
            claimName: hasura-claim1
status: {}
