apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ipfs
  name: ipfs
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
    - name: "4001"
      port: 4001
      targetPort: 4001
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: ipfs
status:
  loadBalancer: {}
