apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ipfs
  name: ipfs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ipfs
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ipfs
    spec:
      containers:
        - image: ipfs/go-ipfs
          name: ipfs
          ports:
            - containerPort: 8080
            - containerPort: 4001
            - containerPort: 5001
          resources: {}
          volumeMounts:
            - mountPath: /data/ipfs
              name: ipfs-claim0
            - mountPath: /export
              name: ipfs-claim1
      restartPolicy: Always
      volumes:
        - name: ipfs-claim0
          persistentVolumeClaim:
            claimName: ipfs-claim0
        - name: ipfs-claim1
          persistentVolumeClaim:
            claimName: ipfs-claim1
status: {}
