apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: liquid
  name: liquid
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: liquid
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: liquid
    spec:
      containers:
        - env:
            - name: LIQUID_PEER_PORT
              value: "7044"
            - name: LIQUID_NODE_PORT
              value: "7045"
            - name: LIQUID_ELECTRS_RPC_PORT
              value: "60401"
            - name: LIQUID_ELECTRS_PORT
              value: "3012"
            - name: LIQUID_BLOCK_PORT
              value: "18606"
            - name: LIQUID_TX_PORT
              value: "18607"
          image: asoltys/liquid:latest
          name: liquid
          ports:
            - containerPort: 18884
            - containerPort: 18886
            - containerPort: 18602
            - containerPort: 18603
          resources: {}
          volumeMounts:
            - name: elements-config
              mountPath: /config/elements.conf
              subPath: elements.conf
      restartPolicy: Always
      volumes:
        - name: elements-config
          configMap:
            name: confelements
status: {}
